import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
// import "../public/css/LocalCss.css";
const inter = Inter({ subsets: ["latin"] });
import Homepage from "../components/home/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Workwise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          // you might need to get a newer version
          src="https://kit.fontawesome.com/fbadad80a0.js"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <Homepage />
    </>
  );
}
